### PR TITLE
check for existence of key before using it

### LINKED ISSUE #280: fix map bug for selecting assets when no assets exist
this part of the code fails because it's missing that key
Screenshot 2023-11-03 at 12 07 13 PM

### PR DESCRIPTION
**Pull request by smcalilly**
## Overview

- closes #280 

### Notes
That bug was happening whenever a phase had no existing assets. This defensive programming measure checks for the existence of the `features` key before trying to access it.

### CODE REVIEW

File: asset_dashboard/static/js/components/maps/SelectAssetsMap.js [hunk 1]
```diff
@@ -71,9 +71,12 @@ function SelectAssetsMap(props) {
 
   function saveGeometries() {
     let existingIDs = []
-    existingGeoms.features.forEach(geom => {
-      existingIDs.push(geom.properties.asset_id)
-    })
+
+    if (existingGeoms && existingGeoms.features) {
+      existingGeoms.features.forEach(geom => {
```
Comment (fgregg) [inline asset_dashboard/static/js/components/maps/SelectAssetsMap.js:76]: looks good!

**Review by fgregg — APPROVED** [review]
